# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testlogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testlogin
pod 'ObjectMapper','~> 3.5.0'
pod 'Alamofire', '4.9.1'
pod 'RxSwift', '~> 5'
pod 'KeychainSwift', '~> 16.0'

end
